version: '3.8'

services:
  spring-app:
    build:
      context: .
    container_name: task-scheduler
    ports:
      - "0000:0000"
    env_file:
      - .env
    environment:
      - SERVER_PORT=0000
      - WEB_URLS=${WEB_URLS}
      - CRON_TIMEOUT=${CRON_TIMEOUT}
      - SENTRY_DSN=${SENTRY_DSN}
    restart: unless-stopped
