name: Deploy to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 17

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Build Spring application
        run: ./gradlew build

      - name: Copy JAR file to Raspberry Pi
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 192.168.1.2
          port: 52622
          username: valik98
          password: mili4ko98
          source: ./task-scheduler/build/libs/task-scheduler-0.0.1-SNAPSHOT.jar
          target: /home/valik98/deployment/

      - name: Deploy to Raspberry Pi
        run: sshpass -p mili4ko98 ssh -p 52622 valik98@192.168.1.2 "bash /home/valik98/deployment/task-scheduler/deploy.sh"
