name: Deploy to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: adopt-hotspot

      - name: Build Spring application
        run: ./gradlew build
        
      - name: List files
        run: cd build/libs && ls
        shell: bash

      - name: Copy JAR file to Raspberry Pi
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 0.tcp.eu.ngrok.io
          port: 10162
          username: valik98
          password: mili4ko98
          source: ./build/libs/task-scheduler.jar
          target: /home/valik98/deployment
          
      - name: Deploy to Raspberry Pi
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 0.tcp.eu.ngrok.io
          port: 10162
          username: valik98
          password: mili4ko98
          script: bash /home/valik98/deployment/task-scheduler/deploy.sh
